---
apiVersion: v1
kind: Service
metadata:
  name: astonvillaservice
  labels:
    name: astonvillaservice
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: astonvilla
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: astonvilladeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: astonvilla
    spec:
      containers:
      - name: astonvilla
        image: 'spbang2018/dockerdemo:av-app-imageV4'
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 15
      